### ISSUE TITLE
建议脚本增加更新功能

### ISSUE THREAD

**Issue by zhenglh0109** [Misaka-blog/Hysteria-script#1]
现在已更新至Releases[v1.0.4]

**Comment by misakano7545** [comment]
> 现在已更新至Releases[v1.0.4]

脚本默认是通过GitHub API，获取并安装最新版的Hysteria
至于你说到的这个问题，目前Hysteria的命令貌似不支持输出当前版本号，因此没办法做更新

**Comment by zhenglh0109** [comment]
谢谢
