### ISSUE TITLE
这个协议可以在heroku上面部署吗?

### ISSUE THREAD

**Issue by dxmaimxd** [Misaka-blog/Hysteria-script#3]
这个协议可以在heroku上面部署吗?

**Comment by misakano7545** [comment]
@dxmaimxd 不行

**Comment by dxmaimxd** [comment]
> @dxmaimxd 不行

好的,谢谢... 暂时heroku我是用workers反代,但是查资料响应太慢了,  那过一会儿我就删了这个issues吧...
